before:
  hooks:
    - go mod tidy
    - go mod download
builds:

  - id: lin-gui
    binary: repcap
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{ .CommitDate }}

  - id: win-gui
    binary: repcap
    env:
      - CGO_ENABLED=1
      - CC=x86_64-w64-mingw32-gcc
    goos:
      - windows
    goarch:
      - amd64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{ .CommitDate }}

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of uname.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
    - goos: windows
      format: zip

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

release:
  #name_template: 'v{{ .Version }}'
  #draft: true
  prerelease: auto
  footer: |
    **Full Changelog**: https://github.com/Lemorz56/repcap/compare/{{ .PreviousTag }}...{{ .Tag }}

    Found a bug? Create an [issue](https://github.com/Lemorz56/repcap/issues)!
    Want to help? [contribute](/contributing).


changelog:
  use: github
  sort: asc
  groups: # Regex use RE2 syntax as defined here: https://github.com/google/re2/wiki/Syntax.
  - title: 'Features'
    regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
    order: 100
  - title: 'Bug fixes'
    regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
    order: 200
  - title: 'Documentation'
    regexp: '^.*?docs(\([[:word:]]+\))??!?:.+$'
    order: 300
  - title: 'Dependency updates'
    regexp: '^.*?(feat|fix|chore)\(deps?.+\)!?:.+$'
    order: 400
  - title: 'Other work'
    order: 999
  filters:
    exclude:
      - '^test:'
      # - '^docs:'

scoops:
  - name: repcap
    url_template: "http://github.com/lemorz56/repcap/releases/{{ .Tag }}/{{ .ArtifactName }}"
    bucket:
      owner: lemorz56
      name: scoop-bucket
      branch: main
      #token: ${{ secrets.SCOOP_TAP_GITHUB_TOKEN }}
    folder: bucket
    homepage: http://github.com/lemorz56/repcap
    description: A tcpreplay like tool with GUI for pcap files with media controls. Built with Go and Tyne.
    license: MIT

# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
